const MOVIES_REQUEST = "MOVIES_REQUEST"
const MOVIES_SUCCESS = "MOVIES_SUCCESS"
const MOVIES_FAILURE = "MOVIES_FAILURE"
const COMING_REQUEST = "COMING_REQUEST"
const COMING_SUCCESS = "COMING_SUCCESS"
const COMING_FAILURE = "COMING_FAILURE"
const LIKE_MOVIE = "LIKE_MOVIE"
const UNLIKE_MOVIE = "UNLIKE_MOVIE"

export {
    MOVIES_REQUEST,
    MOVIES_SUCCESS,
    MOVIES_FAILURE,
    COMING_REQUEST,
    COMING_SUCCESS,
    COMING_FAILURE,
    LIKE_MOVIE,
    UNLIKE_MOVIE,
}